@file:Suppress("FunctionName", "unused")

package org.goodmath.simplex.jmanifold

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

object JManifoldJNI {
    external fun ManifoldManifoldPair_first_set(jarg1: Long, jarg1_: ManifoldManifoldPair, jarg2: Long)
    external fun ManifoldManifoldPair_first_get(jarg1: Long, jarg1_: ManifoldManifoldPair): Long
    external fun ManifoldManifoldPair_second_set(jarg1: Long, jarg1_: ManifoldManifoldPair, jarg2: Long)
    external fun ManifoldManifoldPair_second_get(jarg1: Long, jarg1_: ManifoldManifoldPair): Long
    external fun new_ManifoldManifoldPair(): Long
    external fun delete_ManifoldManifoldPair(jarg1: Long)
    external fun ManifoldVec2_x_set(jarg1: Long, jarg1_: ManifoldVec2, jarg2: Float)
    external fun ManifoldVec2_x_get(jarg1: Long, jarg1_: ManifoldVec2):  Float?
    external fun ManifoldVec2_y_set(jarg1: Long, jarg1_: ManifoldVec2, jarg2: Float)
    external fun ManifoldVec2_y_get(jarg1: Long, jarg1_: ManifoldVec2): Float
    external fun new_ManifoldVec2(): Long
    external fun delete_ManifoldVec2(jarg1: Long)
    external fun ManifoldVec3_x_set(jarg1: Long, jarg1_: ManifoldVec3, jarg2: Float)
    external fun ManifoldVec3_x_get(jarg1: Long, jarg1_: ManifoldVec3): Float
    external fun ManifoldVec3_y_set(jarg1: Long, jarg1_: ManifoldVec3, jarg2: Float)
    external fun ManifoldVec3_y_get(jarg1: Long, jarg1_: ManifoldVec3): Float
    external fun ManifoldVec3_z_set(jarg1: Long, jarg1_: ManifoldVec3, jarg2: Float)
    external fun ManifoldVec3_z_get(jarg1: Long, jarg1_: ManifoldVec3):  Float?
    external fun new_ManifoldVec3(): Long
    external fun delete_ManifoldVec3(jarg1: Long)
    external fun ManifoldIVec3_x_set(jarg1: Long, jarg1_: ManifoldIVec3, jarg2: Int)
    external fun ManifoldIVec3_x_get(jarg1: Long, jarg1_: ManifoldIVec3): Int
    external fun ManifoldIVec3_y_set(jarg1: Long, jarg1_: ManifoldIVec3, jarg2: Int)
    external fun ManifoldIVec3_y_get(jarg1: Long, jarg1_: ManifoldIVec3): Int
    external fun ManifoldIVec3_z_set(jarg1: Long, jarg1_: ManifoldIVec3, jarg2: Int)
    external fun ManifoldIVec3_z_get(jarg1: Long, jarg1_: ManifoldIVec3): Int
    external fun new_ManifoldIVec3(): Long
    external fun delete_ManifoldIVec3(jarg1: Long)
    external fun ManifoldVec4_x_set(jarg1: Long, jarg1_: ManifoldVec4, jarg2: Float)
    external fun ManifoldVec4_x_get(jarg1: Long, jarg1_: ManifoldVec4): Float
    external fun ManifoldVec4_y_set(jarg1: Long, jarg1_: ManifoldVec4, jarg2: Float)
    external fun ManifoldVec4_y_get(jarg1: Long, jarg1_: ManifoldVec4): Float
    external fun ManifoldVec4_z_set(jarg1: Long, jarg1_: ManifoldVec4, jarg2: Float)
    external fun ManifoldVec4_z_get(jarg1: Long, jarg1_: ManifoldVec4): Float
    external fun ManifoldVec4_w_set(jarg1: Long, jarg1_: ManifoldVec4, jarg2: Float)
    external fun ManifoldVec4_w_get(jarg1: Long, jarg1_: ManifoldVec4): Float
    external fun new_ManifoldVec4(): Long
    external fun delete_ManifoldVec4(jarg1: Long)
    external fun ManifoldProperties_surface_area_set(jarg1: Long, jarg1_: ManifoldProperties, jarg2: Float)
    external fun ManifoldProperties_surface_area_get(jarg1: Long, jarg1_: ManifoldProperties): Float
    external fun ManifoldProperties_volume_set(jarg1: Long, jarg1_: ManifoldProperties, jarg2: Float)
    external fun ManifoldProperties_volume_get(jarg1: Long, jarg1_: ManifoldProperties): Float
    external fun new_ManifoldProperties(): Long
    external fun delete_ManifoldProperties(jarg1: Long)
    external fun manifold_simple_polygon(jarg1: Long, jarg2: Long, jarg2_: ManifoldVec2, jarg3: Long): Long
    external fun manifold_polygons(jarg1: Long, jarg2: Long, jarg3: Long): Long
    external fun manifold_simple_polygon_length(jarg1: Long): Long
    external fun manifold_polygons_length(jarg1: Long): Long
    external fun manifold_polygons_simple_length(jarg1: Long, jarg2: Int): Long
    external fun manifold_simple_polygon_get_point(jarg1: Long, jarg2: Int): Long
    external fun manifold_polygons_get_simple(jarg1: Long, jarg2: Long, jarg3: Int): Long
    external fun manifold_polygons_get_point(jarg1: Long, jarg2: Int, jarg3: Int): Long
    external fun manifold_meshgl(jarg1: Long, jarg2: Long, jarg3: Long, jarg4: Long, jarg5: Long, jarg6: Long): Long
    external fun manifold_meshgl_w_tangents(jarg1: Long, jarg2: Long, jarg3: Long, jarg4: Long, jarg5: Long, jarg6: Long, jarg7: Long): Long
    external fun manifold_get_meshgl(jarg1: Long, jarg2: Long): Long
    external fun manifold_meshgl_copy(jarg1: Long, jarg2: Long): Long
    external fun manifold_meshgl_merge(jarg1: Long, jarg2: Long): Long
    external fun manifold_level_set(jarg1: Long, jarg2: Long, jarg3: Long, jarg4: Float, jarg5: Float, jarg6: Float, jarg7: Long): Long
    external fun manifold_level_set_seq(jarg1: Long, jarg2: Long, jarg3: Long, jarg4: Float, jarg5: Float, jarg6: Float, jarg7: Long): Long
    external fun manifold_manifold_empty_vec(jarg1: Long): Long
    external fun manifold_manifold_vec(jarg1: Long, jarg2: Long): Long
    external fun manifold_manifold_vec_reserve(jarg1: Long, jarg2: Long)
    external fun manifold_manifold_vec_length(jarg1: Long): Long
    external fun manifold_manifold_vec_get(jarg1: Long, jarg2: Long, jarg3: Int): Long
    external fun manifold_manifold_vec_set(jarg1: Long, jarg2: Int, jarg3: Long)
    external fun manifold_manifold_vec_push_back(jarg1: Long, jarg2: Long)
    external fun manifold_boolean(jarg1: Long, jarg2: Long, jarg3: Long, jarg4: Int): Long
    external fun manifold_batch_boolean(jarg1: Long, jarg2: Long, jarg3: Int): Long
    external fun manifold_union(jarg1: Long, jarg2: Long, jarg3: Long): Long
    external fun manifold_difference(jarg1: Long, jarg2: Long, jarg3: Long): Long
    external fun manifold_intersection(jarg1: Long, jarg2: Long, jarg3: Long): Long
    external fun manifold_split(jarg1: Long, jarg2: Long, jarg3: Long, jarg4: Long): Long
    external fun manifold_split_by_plane(jarg1: Long, jarg2: Long, jarg3: Long, jarg4: Float, jarg5: Float, jarg6: Float, jarg7: Float): Long
    external fun manifold_trim_by_plane(jarg1: Long, jarg2: Long, jarg3: Float, jarg4: Float, jarg5: Float, jarg6: Float): Long
    external fun manifold_slice(jarg1: Long, jarg2: Long, jarg3: Float): Long
    external fun manifold_project(jarg1: Long, jarg2: Long): Long
    external fun manifold_hull(jarg1: Long, jarg2: Long): Long
    external fun manifold_batch_hull(jarg1: Long, jarg2: Long): Long
    external fun manifold_hull_pts(jarg1: Long, jarg2: Long, jarg2_: ManifoldVec3, jarg3: Long): Long
    external fun manifold_translate(jarg1: Long, jarg2: Long, jarg3: Float, jarg4: Float, jarg5: Float): Long
    external fun manifold_rotate(jarg1: Long, jarg2: Long, jarg3: Float, jarg4: Float, jarg5: Float): Long
    external fun manifold_scale(jarg1: Long, jarg2: Long, jarg3: Float, jarg4: Float, jarg5: Float): Long
    external fun manifold_transform(jarg1: Long, jarg2: Long, jarg3: Float, jarg4: Float, jarg5: Float, jarg6: Float, jarg7: Float, jarg8: Float, jarg9: Float, jarg10: Float, jarg11: Float, jarg12: Float, jarg13: Float, jarg14: Float): Long
    external fun manifold_mirror(jarg1: Long, jarg2: Long, jarg3: Float, jarg4: Float, jarg5: Float): Long
    external fun manifold_warp(jarg1: Long, jarg2: Long, jarg3: Long, jarg4: Long): Long
    external fun manifold_smooth_by_normals(jarg1: Long, jarg2: Long, jarg3: Int): Long
    external fun manifold_smooth_out(jarg1: Long, jarg2: Long, jarg3: Float, jarg4: Float): Long
    external fun manifold_refine(jarg1: Long, jarg2: Long, jarg3: Int): Long
    external fun manifold_refine_to_length(jarg1: Long, jarg2: Long, jarg3: Float): Long
    external fun manifold_empty(jarg1: Long): Long
    external fun manifold_copy(jarg1: Long, jarg2: Long): Long
    external fun manifold_tetrahedron(jarg1: Long): Long
    external fun manifold_cube(jarg1: Long, jarg2: Float, jarg3: Float, jarg4: Float, jarg5: Int): Long
    external fun manifold_cylinder(jarg1: Long, jarg2: Float, jarg3: Float, jarg4: Float, jarg5: Int, jarg6: Int): Long
    external fun manifold_sphere(jarg1: Long, jarg2: Float, jarg3: Int): Long
    external fun manifold_of_meshgl(jarg1: Long, jarg2: Long): Long
    external fun manifold_smooth(jarg1: Long, jarg2: Long, jarg3: Long, jarg4: Long, jarg5: Long): Long
    external fun manifold_extrude(jarg1: Long, jarg2: Long, jarg3: Float, jarg4: Int, jarg5: Float, jarg6: Float, jarg7: Float): Long
    external fun manifold_revolve(jarg1: Long, jarg2: Long, jarg3: Int): Long
    external fun manifold_compose(jarg1: Long, jarg2: Long): Long
    external fun manifold_decompose(jarg1: Long, jarg2: Long): Long
    external fun manifold_as_original(jarg1: Long, jarg2: Long): Long
    external fun manifold_is_empty(jarg1: Long): Int
    external fun manifold_status(jarg1: Long): Int
    external fun manifold_num_vert(jarg1: Long): Int
    external fun manifold_num_edge(jarg1: Long): Int
    external fun manifold_num_tri(jarg1: Long): Int
    external fun manifold_bounding_box(jarg1: Long, jarg2: Long): Long
    external fun manifold_precision(jarg1: Long): Float
    external fun manifold_genus(jarg1: Long): Int
    external fun manifold_get_properties(jarg1: Long): Long
    external fun manifold_get_circular_segments(jarg1: Float): Int
    external fun manifold_original_id(jarg1: Long): Int
    external fun manifold_reserve_ids(jarg1: Long): Long
    external fun manifold_set_properties(jarg1: Long, jarg2: Long, jarg3: Int, jarg4: Long, jarg5: Long): Long
    external fun manifold_calculate_curvature(jarg1: Long, jarg2: Long, jarg3: Int, jarg4: Int): Long
    external fun manifold_min_gap(jarg1: Long, jarg2: Long, jarg3: Float): Float
    external fun manifold_calculate_normals(jarg1: Long, jarg2: Long, jarg3: Int, jarg4: Int): Long
    external fun manifold_cross_section_empty(jarg1: Long): Long
    external fun manifold_cross_section_copy(jarg1: Long, jarg2: Long): Long
    external fun manifold_cross_section_of_simple_polygon(jarg1: Long, jarg2: Long, jarg3: Int): Long
    external fun manifold_cross_section_of_polygons(jarg1: Long, jarg2: Long, jarg3: Int): Long
    external fun manifold_cross_section_square(jarg1: Long, jarg2: Float, jarg3: Float, jarg4: Int): Long
    external fun manifold_cross_section_circle(jarg1: Long, jarg2: Float, jarg3: Int): Long
    external fun manifold_cross_section_compose(jarg1: Long, jarg2: Long): Long
    external fun manifold_cross_section_decompose(jarg1: Long, jarg2: Long): Long
    external fun manifold_cross_section_empty_vec(jarg1: Long): Long
    external fun manifold_cross_section_vec(jarg1: Long, jarg2: Long): Long
    external fun manifold_cross_section_vec_reserve(jarg1: Long, jarg2: Long)
    external fun manifold_cross_section_vec_length(jarg1: Long): Long
    external fun manifold_cross_section_vec_get(jarg1: Long, jarg2: Long, jarg3: Int): Long
    external fun manifold_cross_section_vec_set(jarg1: Long, jarg2: Int, jarg3: Long)
    external fun manifold_cross_section_vec_push_back(jarg1: Long, jarg2: Long)
    external fun manifold_cross_section_boolean(jarg1: Long, jarg2: Long, jarg3: Long, jarg4: Int): Long
    external fun manifold_cross_section_batch_boolean(jarg1: Long, jarg2: Long, jarg3: Int): Long
    external fun manifold_cross_section_union(jarg1: Long, jarg2: Long, jarg3: Long): Long
    external fun manifold_cross_section_difference(jarg1: Long, jarg2: Long, jarg3: Long): Long
    external fun manifold_cross_section_intersection(jarg1: Long, jarg2: Long, jarg3: Long): Long
    external fun manifold_cross_section_hull(jarg1: Long, jarg2: Long): Long
    external fun manifold_cross_section_batch_hull(jarg1: Long, jarg2: Long): Long
    external fun manifold_cross_section_hull_simple_polygon(jarg1: Long, jarg2: Long): Long
    external fun manifold_cross_section_hull_polygons(jarg1: Long, jarg2: Long): Long
    external fun manifold_cross_section_translate(jarg1: Long, jarg2: Long, jarg3: Float, jarg4: Float): Long
    external fun manifold_cross_section_rotate(jarg1: Long, jarg2: Long, jarg3: Float): Long
    external fun manifold_cross_section_scale(jarg1: Long, jarg2: Long, jarg3: Float, jarg4: Float): Long
    external fun manifold_cross_section_mirror(jarg1: Long, jarg2: Long, jarg3: Float, jarg4: Float): Long
    external fun manifold_cross_section_transform(jarg1: Long, jarg2: Long, jarg3: Float, jarg4: Float, jarg5: Float, jarg6: Float, jarg7: Float, jarg8: Float): Long
    external fun manifold_cross_section_warp(jarg1: Long, jarg2: Long, jarg3: Long): Long
    external fun manifold_cross_section_warp_context(jarg1: Long, jarg2: Long, jarg3: Long, jarg4: Long): Long
    external fun manifold_cross_section_simplify(jarg1: Long, jarg2: Long, jarg3: Double): Long
    external fun manifold_cross_section_offset(jarg1: Long, jarg2: Long, jarg3: Double, jarg4: Int, jarg5: Double, jarg6: Int): Long
    external fun manifold_cross_section_area(jarg1: Long): Double
    external fun manifold_cross_section_num_vert(jarg1: Long): Int
    external fun manifold_cross_section_num_contour(jarg1: Long): Int
    external fun manifold_cross_section_is_empty(jarg1: Long): Int
    external fun manifold_cross_section_bounds(jarg1: Long, jarg2: Long): Long
    external fun manifold_cross_section_to_polygons(jarg1: Long, jarg2: Long): Long
    external fun manifold_rect(jarg1: Long, jarg2: Float, jarg3: Float, jarg4: Float, jarg5: Float): Long
    external fun manifold_rect_min(jarg1: Long): Long
    external fun manifold_rect_max(jarg1: Long): Long
    external fun manifold_rect_dimensions(jarg1: Long): Long
    external fun manifold_rect_center(jarg1: Long): Long
    external fun manifold_rect_scale(jarg1: Long): Float
    external fun manifold_rect_contains_pt(jarg1: Long, jarg2: Float, jarg3: Float): Int
    external fun manifold_rect_contains_rect(jarg1: Long, jarg2: Long): Int
    external fun manifold_rect_include_pt(jarg1: Long, jarg2: Float, jarg3: Float)
    external fun manifold_rect_union(jarg1: Long, jarg2: Long, jarg3: Long): Long
    external fun manifold_rect_transform(jarg1: Long, jarg2: Long, jarg3: Float, jarg4: Float, jarg5: Float, jarg6: Float, jarg7: Float, jarg8: Float): Long
    external fun manifold_rect_translate(jarg1: Long, jarg2: Long, jarg3: Float, jarg4: Float): Long
    external fun manifold_rect_mul(jarg1: Long, jarg2: Long, jarg3: Float, jarg4: Float): Long
    external fun manifold_rect_does_overlap_rect(jarg1: Long, jarg2: Long): Int
    external fun manifold_rect_is_empty(jarg1: Long): Int
    external fun manifold_rect_is_finite(jarg1: Long): Int
    external fun manifold_box(jarg1: Long, jarg2: Float, jarg3: Float, jarg4: Float, jarg5: Float, jarg6: Float, jarg7: Float): Long
    external fun manifold_box_min(jarg1: Long): Long
    external fun manifold_box_max(jarg1: Long): Long
    external fun manifold_box_dimensions(jarg1: Long): Long
    external fun manifold_box_center(jarg1: Long): Long
    external fun manifold_box_scale(jarg1: Long): Float
    external fun manifold_box_contains_pt(jarg1: Long, jarg2: Float, jarg3: Float, jarg4: Float): Int
    external fun manifold_box_contains_box(jarg1: Long, jarg2: Long): Int
    external fun manifold_box_include_pt(jarg1: Long, jarg2: Float, jarg3: Float, jarg4: Float)
    external fun manifold_box_union(jarg1: Long, jarg2: Long, jarg3: Long): Long
    external fun manifold_box_transform(jarg1: Long, jarg2: Long, jarg3: Float, jarg4: Float, jarg5: Float, jarg6: Float, jarg7: Float, jarg8: Float, jarg9: Float, jarg10: Float, jarg11: Float, jarg12: Float, jarg13: Float, jarg14: Float): Long
    external fun manifold_box_translate(jarg1: Long, jarg2: Long, jarg3: Float, jarg4: Float, jarg5: Float): Long
    external fun manifold_box_mul(jarg1: Long, jarg2: Long, jarg3: Float, jarg4: Float, jarg5: Float): Long
    external fun manifold_box_does_overlap_pt(jarg1: Long, jarg2: Float, jarg3: Float, jarg4: Float): Int
    external fun manifold_box_does_overlap_box(jarg1: Long, jarg2: Long): Int
    external fun manifold_box_is_finite(jarg1: Long): Int
    external fun manifold_set_min_circular_angle(jarg1: Float)
    external fun manifold_set_min_circular_edge_length(jarg1: Float)
    external fun manifold_set_circular_segments(jarg1: Int)
    external fun manifold_meshgl_num_prop(jarg1: Long): Int
    external fun manifold_meshgl_num_vert(jarg1: Long): Int
    external fun manifold_meshgl_num_tri(jarg1: Long): Int
    external fun manifold_meshgl_vert_properties_length(jarg1: Long): Long
    external fun manifold_meshgl_tri_length(jarg1: Long): Long
    external fun manifold_meshgl_merge_length(jarg1: Long): Long
    external fun manifold_meshgl_run_index_length(jarg1: Long): Long
    external fun manifold_meshgl_run_original_id_length(jarg1: Long): Long
    external fun manifold_meshgl_run_transform_length(jarg1: Long): Long
    external fun manifold_meshgl_face_id_length(jarg1: Long): Long
    external fun manifold_meshgl_tangent_length(jarg1: Long): Long
    external fun manifold_meshgl_vert_properties(jarg1: Long, jarg2: Long): Long
    external fun manifold_meshgl_tri_verts(jarg1: Long, jarg2: Long): Long
    external fun manifold_meshgl_merge_from_vert(jarg1: Long, jarg2: Long): Long
    external fun manifold_meshgl_merge_to_vert(jarg1: Long, jarg2: Long): Long
    external fun manifold_meshgl_run_index(jarg1: Long, jarg2: Long): Long
    external fun manifold_meshgl_run_original_id(jarg1: Long, jarg2: Long): Long
    external fun manifold_meshgl_run_transform(jarg1: Long, jarg2: Long): Long
    external fun manifold_meshgl_face_id(jarg1: Long, jarg2: Long): Long
    external fun manifold_meshgl_halfedge_tangent(jarg1: Long, jarg2: Long): Long
    external fun manifold_manifold_size(): Long
    external fun manifold_manifold_vec_size(): Long
    external fun manifold_cross_section_size(): Long
    external fun manifold_cross_section_vec_size(): Long
    external fun manifold_simple_polygon_size(): Long
    external fun manifold_polygons_size(): Long
    external fun manifold_manifold_pair_size(): Long
    external fun manifold_meshgl_size(): Long
    external fun manifold_box_size(): Long
    external fun manifold_rect_size(): Long
    external fun manifold_curvature_size(): Long
    external fun manifold_destruct_manifold(jarg1: Long)
    external fun manifold_destruct_manifold_vec(jarg1: Long)
    external fun manifold_destruct_cross_section(jarg1: Long)
    external fun manifold_destruct_cross_section_vec(jarg1: Long)
    external fun manifold_destruct_simple_polygon(jarg1: Long)
    external fun manifold_destruct_polygons(jarg1: Long)
    external fun manifold_destruct_meshgl(jarg1: Long)
    external fun manifold_destruct_box(jarg1: Long)
    external fun manifold_destruct_rect(jarg1: Long)
    external fun manifold_delete_manifold(jarg1: Long)
    external fun manifold_delete_manifold_vec(jarg1: Long)
    external fun manifold_delete_cross_section(jarg1: Long)
    external fun manifold_delete_cross_section_vec(jarg1: Long)
    external fun manifold_delete_simple_polygon(jarg1: Long)
    external fun manifold_delete_polygons(jarg1: Long)
    external fun manifold_delete_meshgl(jarg1: Long)
    external fun manifold_delete_box(jarg1: Long)
    external fun manifold_delete_rect(jarg1: Long)
}

