/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.goodmath.simplex.jmanifold

class ManifoldVec4(@Transient var swigCPtr: Long, @Transient var swigCMemOwn: Boolean) {

    companion object {
        fun swigRelease(obj: ManifoldVec4?): Long {
            var ptr: Long = 0
            if (obj != null) {
                if (!obj.swigCMemOwn) {
                    throw RuntimeException("Cannot release ownership as memory is not owned")
                }
                ptr = obj.swigCPtr
                obj.swigCMemOwn = false
                obj.delete()
            }
            return ptr
        }

        fun getCPtr(obj: ManifoldVec3?): Long {
            return obj?.swigCPtr ?: 0L
        }
    }


  @Suppress("removal")
  fun finalize() {
    delete()
  }


    @Synchronized fun delete() {
        if (swigCPtr != 0L) {
            if (swigCMemOwn) {
                swigCMemOwn = false
                JManifoldJNI.delete_ManifoldVec3(swigCPtr)
            }
            swigCPtr = 0
        }
    }


  public fun setX(value: Float) {
    JManifoldJNI.ManifoldVec4_x_set(swigCPtr, this, value);
  }

  public fun getX(): Float {
    return JManifoldJNI.ManifoldVec4_x_get(swigCPtr, this);
  }

  public fun setY(value: Float) {
    JManifoldJNI.ManifoldVec4_y_set(swigCPtr, this, value);
  }

  public fun getY(): Float {
    return JManifoldJNI.ManifoldVec4_y_get(swigCPtr, this);
  }

  public fun setZ(value: Float) {
    JManifoldJNI.ManifoldVec4_z_set(swigCPtr, this, value);
  }

  public fun getZ(): Float {
    return JManifoldJNI.ManifoldVec4_z_get(swigCPtr, this);
  }

  public fun setW(value: Float) {
    JManifoldJNI.ManifoldVec4_w_set(swigCPtr, this, value);
  }

  public fun getW(): Float {
    return JManifoldJNI.ManifoldVec4_w_get(swigCPtr, this);
  }

  constructor(): this(JManifoldJNI.new_ManifoldVec4(), true)

}
