/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.goodmath.simplex.jmanifold

class ManifoldIVec3(var swigCPtr: Long, var swigCMemOwn: Boolean) {

    companion object {
        fun getCPtr(obj: ManifoldIVec3?): Long {
            return obj?.swigCPtr ?: 0
        }

        fun swigRelease(obj: ManifoldIVec3): Long {
            var ptr: Long = 0L
            if (obj != null) {
                if (!obj.swigCMemOwn) {
                    throw RuntimeException("Cannot release ownership as memory is not owned")
                }
                ptr = obj.swigCPtr
                obj.swigCMemOwn = false
                obj.delete()
            }
            return ptr
        }
    }

    @Suppress("removal")
    fun finalize() {
        delete()
    }

    @Synchronized
    fun delete() {
        if (swigCPtr != 0L) {
            if (swigCMemOwn) {
                swigCMemOwn = false;
            }
            JManifoldJNI.delete_ManifoldIVec3(swigCPtr);
        }
        swigCPtr = 0;
    }

    fun setX(value: Int) {
        JManifoldJNI.ManifoldIVec3_x_set(swigCPtr, this, value);
    }

    fun getX(): Int {
        return JManifoldJNI.ManifoldIVec3_x_get(swigCPtr, this);
    }

    fun setY(value: Int) {
        JManifoldJNI.ManifoldIVec3_y_set(swigCPtr, this, value);
    }

    fun getY(): Int {
        return JManifoldJNI.ManifoldIVec3_y_get(swigCPtr, this);
    }

    fun setZ(value : Int) {
        JManifoldJNI.ManifoldIVec3_z_set(swigCPtr, this, value);
    }

    fun getZ(): Int {
        return JManifoldJNI.ManifoldIVec3_z_get(swigCPtr, this);
    }

    constructor() : this(JManifoldJNI.new_ManifoldIVec3(), true)

}
