/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.goodmath.simplex.jmanifold

class ManifoldError(val swigName: String, val swigValue: Int) {

    constructor(swigName: String, swigEnum: ManifoldError) : this(swigName, swigEnum.swigValue) {
        swigNext = this.swigValue + 1;
    }

    constructor(swigName: String): this(swigName, swigNext++)

    companion object {
        val MANIFOLD_NO_ERROR = ManifoldError("MANIFOLD_NO_ERROR");
        val MANIFOLD_NON_FINITE_VERTEX = ManifoldError("MANIFOLD_NON_FINITE_VERTEX");
        val MANIFOLD_NOT_MANIFOLD = ManifoldError("MANIFOLD_NOT_MANIFOLD");
        val MANIFOLD_VERTEX_INDEX_OUT_OF_BOUNDS = ManifoldError("MANIFOLD_VERTEX_INDEX_OUT_OF_BOUNDS");
        val MANIFOLD_PROPERTIES_WRONG_LENGTH = ManifoldError("MANIFOLD_PROPERTIES_WRONG_LENGTH");
        val MANIFOLD_MISSING_POSITION_PROPERTIES = ManifoldError("MANIFOLD_MISSING_POSITION_PROPERTIES");
        val MANIFOLD_MERGE_VECTORS_DIFFERENT_LENGTHS = ManifoldError("MANIFOLD_MERGE_VECTORS_DIFFERENT_LENGTHS");
        val MANIFOLD_MERGE_INDEX_OUT_OF_BOUNDS = ManifoldError("MANIFOLD_MERGE_INDEX_OUT_OF_BOUNDS");
        val MANIFOLD_TRANSFORM_WRONG_LENGTH = ManifoldError("MANIFOLD_TRANSFORM_WRONG_LENGTH");
        val MANIFOLD_RUN_INDEX_WRONG_LENGTH = ManifoldError("MANIFOLD_RUN_INDEX_WRONG_LENGTH");
        val MANIFOLD_FACE_ID_WRONG_LENGTH = ManifoldError("MANIFOLD_FACE_ID_WRONG_LENGTH");
        val MANIFOLD_INVALID_CONSTRUCTION = ManifoldError("MANIFOLD_INVALID_CONSTRUCTION");
        val swigValues: List<ManifoldError> = listOf(MANIFOLD_NO_ERROR, MANIFOLD_NON_FINITE_VERTEX, MANIFOLD_NOT_MANIFOLD, MANIFOLD_VERTEX_INDEX_OUT_OF_BOUNDS, MANIFOLD_PROPERTIES_WRONG_LENGTH, MANIFOLD_MISSING_POSITION_PROPERTIES, MANIFOLD_MERGE_VECTORS_DIFFERENT_LENGTHS, MANIFOLD_MERGE_INDEX_OUT_OF_BOUNDS, MANIFOLD_TRANSFORM_WRONG_LENGTH, MANIFOLD_RUN_INDEX_WRONG_LENGTH, MANIFOLD_FACE_ID_WRONG_LENGTH, MANIFOLD_INVALID_CONSTRUCTION)

        fun swigToEnum(swigValue: Int): ManifoldError {
            if (swigValue < swigValues.size && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
                return swigValues[swigValue];
            for (i in 0..< swigValues.size) {
                if (swigValues[i].swigValue == swigValue)
                    return swigValues[i];
            }
            throw IllegalArgumentException("No enum ManifoldError with value $swigValue")
        }


        var swigNext: Int = 0
    }


    override fun  toString(): String {
        return swigName;
    }
}

