package org.goodmath.simplex.jmanifold
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


@Suppress("removal")
class ManifoldVec2(@Transient var swigCPtr: Long, @Transient var swigCMemOwn: Boolean) {

    companion object {
        fun getCPtr(obj: ManifoldVec2?): Long {
            return obj?.swigCPtr ?: 0
        }

        fun swigRelease(obj: ManifoldVec2?): Long {
            var ptr: Long = 0
            if (obj != null) {
                if (!obj.swigCMemOwn) {
                    throw RuntimeException("Cannot release ownership as memory is not owned")
                }
                ptr = obj.swigCPtr
                obj.swigCMemOwn = false
                obj.delete()
            }
            return ptr
        }
    }


    fun finalize() {
        delete();
    }

    @Synchronized
    fun delete() {
        if (swigCPtr != 0L) {
            if (swigCMemOwn) {
                swigCMemOwn = false
                JManifoldJNI.delete_ManifoldVec2(swigCPtr)
            }
            swigCPtr = 0
        }
    }

    fun setX(value: Float) {
        JManifoldJNI.ManifoldVec2_x_set(swigCPtr, this, value);
    }

    fun getX(): Float {
        return JManifoldJNI.ManifoldVec2_x_get(swigCPtr, this);
    }

    fun setY(value: Float) {
        JManifoldJNI.ManifoldVec2_y_set(swigCPtr, this, value);
    }

    fun getY(): Float {
        return JManifoldJNI.ManifoldVec2_y_get(swigCPtr, this);
    }

    constructor() : this(JManifoldJNI.new_ManifoldVec2(), true) {}

}
