/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.goodmath.simplex.jmanifold

class SWIGTYPE_p_ManifoldManifold(@Transient var swigCPtr: Long) {
    constructor(cPtr: Long, futureUse: Boolean) : this(cPtr)

  constructor(): this(0L)

    companion object {
        fun getCPtr(obj: SWIGTYPE_p_ManifoldManifold?): Long =
            obj?.swigCPtr ?: 0

        fun swigRelease(obj: SWIGTYPE_p_ManifoldManifold?): Long = obj?.swigCPtr ?: 0
    }
}

