/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.goodmath.simplex.jmanifold

class SWIGTYPE_p_f_p_float_ManifoldVec3_p_q_const__float_p_void__void(@Transient var swigCPtr: Long) {

    constructor(cPtr: Long, futureUse: Boolean): this(cPtr)

    constructor(): this(0L)

    companion object {
        fun getCPtr(obj: SWIGTYPE_p_f_p_float_ManifoldVec3_p_q_const__float_p_void__void?): Long = obj?.swigCPtr ?: 0

        fun swigRelease(obj: SWIGTYPE_p_f_p_float_ManifoldVec3_p_q_const__float_p_void__void?): Long = obj?.swigCPtr ?: 0
    }
}

